const SITE_CONFIG={bookingScore:'8.9/10',googleScore:'4.7/5',yearsExperience:'+20'};
const APARTMENTS=[
{n:'1',name:'Apartamento N.º 1',desc:'Amplio y familiar',people:'7 personas',beds:'2 dormitorios',img:'images/apto-09-salon-amplio.jpg'},
{n:'2',name:'Apartamento N.º 2',desc:'Luminoso y cómodo',people:'4 personas',beds:'1 dormitorio',img:'images/apto-01-vista-mar.jpg'},
{n:'3',name:'Apartamento N.º 3',desc:'Ideal pareja o familia pequeña',people:'4 personas',beds:'1 dormitorio',img:'images/apto-02-salon-regatas.jpg'},
{n:'4',name:'Apartamento N.º 4',desc:'Terraza y espacio familiar',people:'6 personas',beds:'1 dormitorio',img:'images/apto-04-comedor-terraza.jpg'},
{n:'5',name:'Estudio N.º 5',desc:'Perfecto para pareja',people:'2 personas',beds:'Estudio',img:'images/apto-05-salon-calas.jpg'},
{n:'6',name:'Apartamento N.º 6',desc:'Funcional y mediterráneo',people:'4 personas',beds:'1 dormitorio',img:'images/apto-06-salon-velero.jpg'},
{n:'7',name:'Apartamento N.º 7',desc:'Para familias',people:'6 personas',beds:'2 dormitorios',img:'images/apto-08-salon-panoramica.jpg'},
{n:'8',name:'Apartamento N.º 8',desc:'Espacioso',people:'7 personas',beds:'2 dormitorios',img:'images/apto-09-salon-amplio.jpg'},
{n:'9',name:'Apartamento N.º 9',desc:'Máxima capacidad',people:'8 personas',beds:'3 dormitorios',img:'images/apto-03-salon-l-mar.jpg'},
{n:'10',name:'Apartamento N.º 10',desc:'Vacaciones en grupo',people:'6 personas',beds:'2 dormitorios',img:'images/apto-04-comedor-terraza.jpg'},
{n:'11',name:'Apartamento N.º 11',desc:'Salón amplio',people:'6 personas',beds:'1 dormitorio',img:'images/apto-05-salon-calas.jpg'},
{n:'12',name:'Dúplex N.º 12',desc:'Dúplex familiar',people:'6 personas',beds:'2 dormitorios',img:'images/apto-06-salon-velero.jpg'},
{n:'13',name:'Dúplex N.º 13',desc:'Dúplex con carácter',people:'6 personas',beds:'2 dormitorios',img:'images/apto-08-salon-panoramica.jpg'},
{n:'14',name:'Apartamento N.º 14',desc:'Cómodo y práctico',people:'6 personas',beds:'2 dormitorios',img:'images/apto-02-salon-regatas.jpg'},
{n:'15',name:'Apartamento N.º 15',desc:'Vacaciones familiares',people:'6 personas',beds:'2 dormitorios',img:'images/apto-01-vista-mar.jpg'}
];
const TESTIMONIALS=['Perfecto para familias. No usamos el coche en toda la semana.','La compra preparada fue una gran comodidad.','Ubicación excelente y trato muy cercano.'];
function initScores(){document.getElementById('bookingScore').textContent=SITE_CONFIG.bookingScore;document.getElementById('googleScore').textContent=SITE_CONFIG.googleScore;document.getElementById('yearsExperience').textContent=SITE_CONFIG.yearsExperience}
function renderApartments(){const grid=document.getElementById('aptGrid');if(!grid)return;grid.innerHTML=APARTMENTS.map(a=>`<article class="apt-mini reveal"><img src="${a.img}" alt="${a.name} en Apartaments El Bergantí, Canyelles Petites" loading="lazy"><div><span class="apt-number">Nº ${a.n}</span><h3>${a.name}</h3><p>${a.desc}</p><ul><li>👥 ${a.people}</li><li>🛏️ ${a.beds}</li><li>🏖️ Playa a 50 m</li></ul><a href="https://wa.me/34696906510?text=Hola%2C%20quiero%20consultar%20disponibilidad%20del%20${encodeURIComponent(a.name)}" class="mini-link">Consultar →</a></div></article>`).join('')}
function initNav(){const nav=document.getElementById('nav'),burger=document.getElementById('burger'),menu=document.getElementById('mobileMenu');window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',window.scrollY>20),{passive:true});burger?.addEventListener('click',()=>menu.classList.toggle('open'));menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')))}
function initReveal(){const items=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){items.forEach(i=>i.classList.add('show'));return}const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}})},{threshold:.12});items.forEach(i=>io.observe(i))}
function initReviews(){let current=0;const text=document.getElementById('reviewText'),dots=document.getElementById('reviewDots'),prev=document.getElementById('prevReview'),next=document.getElementById('nextReview');if(!text||!dots)return;function paint(){text.textContent=TESTIMONIALS[current];dots.innerHTML=TESTIMONIALS.map((_,i)=>`<i class="review-dot ${i===current?'on':''}"></i>`).join('')}prev?.addEventListener('click',()=>{current=(current-1+TESTIMONIALS.length)%TESTIMONIALS.length;paint()});next?.addEventListener('click',()=>{current=(current+1)%TESTIMONIALS.length;paint()});setInterval(()=>{current=(current+1)%TESTIMONIALS.length;paint()},6500);paint()}
function applyI18n(lang){const dict=(window.I18N&&window.I18N[lang])?window.I18N[lang]:window.I18N?.es;if(!dict)return;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(dict[key])el.textContent=dict[key]});document.querySelectorAll('[data-i18n-html]').forEach(el=>{const key=el.dataset.i18nHtml;if(dict[key])el.innerHTML=dict[key]});document.querySelectorAll('[data-lang]').forEach(a=>a.classList.toggle('on',a.dataset.lang===lang));localStorage.setItem('bergantiLang',lang)}
function initLang(){const saved=localStorage.getItem('bergantiLang')||'es';applyI18n(saved);document.querySelectorAll('[data-lang]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();applyI18n(a.dataset.lang)}))}
document.addEventListener('DOMContentLoaded',()=>{initScores();renderApartments();initNav();initReviews();initLang();initReveal()});
