const SITE_CONFIG={bookingScore:'8.9/10',googleScore:'4.7/5',yearsExperience:'+20'};
const APARTMENTS=[
{n:'1',name:'Apartamento N.º 1',desc:'Amplio y familiar',people:'7 personas',beds:'2 dormitorios',img:'images/apto-09-salon-amplio.jpg'},
{n:'2',name:'Apartamento N.º 2',desc:'Luminoso y cómodo',people:'4 personas',beds:'1 dormitorio',img:'images/apto-01-vista-mar.jpg'},
{n:'3',name:'Apartamento N.º 3',desc:'Ideal pareja o familia pequeña',people:'4 personas',beds:'1 dormitorio',img:'images/apto-02-salon-regatas.jpg'},
{n:'4',name:'Apartamento N.º 4',desc:'Terraza y espacio familiar',people:'6 personas',beds:'1 dormitorio',img:'images/apto-04-comedor-terraza.jpg'},
{n:'5',name:'Estudio N.º 5',desc:'Perfecto para pareja',people:'2 personas',beds:'Estudio',img:'images/apto-05-salon-calas.jpg'},
{n:'6',name:'Apartamento N.º 6',desc:'Funcional y mediterráneo',people:'4 personas',beds:'1 dormitorio',img:'images/apto-06-salon-velero.jpg'},
{n:'7',name:'Apartamento N.º 7',desc:'Para familias',people:'6 personas',beds:'2 dormitorios',img:'images/apto-08-salon-panoramica.jpg'},
{n:'8',name:'Apartamento N.º 8',desc:'Espacioso',people:'7 personas',beds:'2 dormitorios',img:'images/apto-09-salon-amplio.jpg'},
{n:'9',name:'Apartamento N.º 9',desc:'Máxima capacidad',people:'8 personas',beds:'3 dormitorios',img:'images/apto-03-salon-l-mar.jpg'},
{n:'10',name:'Apartamento N.º 10',desc:'Vacaciones en grupo',people:'6 personas',beds:'2 dormitorios',img:'images/apto-04-comedor-terraza.jpg'},
{n:'11',name:'Apartamento N.º 11',desc:'Salón amplio',people:'6 personas',beds:'1 dormitorio',img:'images/apto-05-salon-calas.jpg'},
{n:'12',name:'Dúplex N.º 12',desc:'Dúplex familiar',people:'6 personas',beds:'2 dormitorios',img:'images/apto-06-salon-velero.jpg'},
{n:'13',name:'Dúplex N.º 13',desc:'Dúplex con carácter',people:'6 personas',beds:'2 dormitorios',img:'images/apto-08-salon-panoramica.jpg'},
{n:'14',name:'Apartamento N.º 14',desc:'Cómodo y práctico',people:'6 personas',beds:'2 dormitorios',img:'images/apto-02-salon-regatas.jpg'},
{n:'15',name:'Apartamento N.º 15',desc:'Vacaciones familiares',people:'6 personas',beds:'2 dormitorios',img:'images/apto-01-vista-mar.jpg'}
];
const TESTIMONIALS={
es:['Perfecto para familias. No usamos el coche en toda la semana.','La compra preparada fue una gran comodidad.','Ubicación excelente y trato muy cercano.'],
ca:['Perfecte per a famílies. No vam fer servir el cotxe en tota la setmana.','La compra preparada va ser una gran comoditat.','Ubicació excel·lent i tracte molt proper.'],
fr:['Parfait pour les familles. Nous n’avons pas utilisé la voiture de toute la semaine.','Les courses préparées ont été un vrai confort.','Emplacement excellent et accueil très chaleureux.'],
en:['Perfect for families. We did not use the car all week.','The prepared shopping service was very convenient.','Excellent location and very personal service.'],
de:['Perfekt für Familien. Wir haben das Auto die ganze Woche nicht benutzt.','Der vorbereitete Einkauf war sehr praktisch.','Ausgezeichnete Lage und sehr persönlicher Service.'],
nl:['Perfect voor gezinnen. We hebben de auto de hele week niet gebruikt.','De voorbereide boodschappen waren erg handig.','Uitstekende locatie en zeer persoonlijke service.']
};
const APT_LANG={
es:{apartment:'Apartamento',studio:'Estudio',duplex:'Dúplex',people:'personas',bedroom:'dormitorio',bedrooms:'dormitorios',beach:'Playa a 50 m',consult:'Consultar',descs:['Amplio y familiar','Luminoso y cómodo','Ideal pareja o familia pequeña','Terraza y espacio familiar','Perfecto para pareja','Funcional y mediterráneo','Para familias','Espacioso','Máxima capacidad','Vacaciones en grupo','Salón amplio','Dúplex familiar','Dúplex con carácter','Cómodo y práctico','Vacaciones familiares']},
ca:{apartment:'Apartament',studio:'Estudi',duplex:'Dúplex',people:'persones',bedroom:'dormitori',bedrooms:'dormitoris',beach:'Platja a 50 m',consult:'Consultar',descs:['Ampli i familiar','Lluminós i còmode','Ideal per a parella o família petita','Terrassa i espai familiar','Perfecte per a parella','Funcional i mediterrani','Per a famílies','Espaiós','Màxima capacitat','Vacances en grup','Sala d’estar àmplia','Dúplex familiar','Dúplex amb caràcter','Còmode i pràctic','Vacances familiars']},
fr:{apartment:'Appartement',studio:'Studio',duplex:'Duplex',people:'personnes',bedroom:'chambre',bedrooms:'chambres',beach:'Plage à 50 m',consult:'Consulter',descs:['Spacieux et familial','Lumineux et confortable','Idéal pour couple ou petite famille','Terrasse et espace familial','Parfait pour un couple','Fonctionnel et méditerranéen','Pour les familles','Spacieux','Capacité maximale','Vacances en groupe','Salon spacieux','Duplex familial','Duplex avec caractère','Confortable et pratique','Vacances en famille']},
en:{apartment:'Apartment',studio:'Studio',duplex:'Duplex',people:'people',bedroom:'bedroom',bedrooms:'bedrooms',beach:'Beach 50 m away',consult:'Check',descs:['Spacious and family-friendly','Bright and comfortable','Ideal for a couple or small family','Terrace and family space','Perfect for a couple','Practical and Mediterranean','For families','Spacious','Maximum capacity','Group holidays','Large living room','Family duplex','Duplex with character','Comfortable and practical','Family holidays']},
de:{apartment:'Apartment',studio:'Studio',duplex:'Duplex',people:'Personen',bedroom:'Schlafzimmer',bedrooms:'Schlafzimmer',beach:'Strand 50 m entfernt',consult:'Anfragen',descs:['Geräumig und familienfreundlich','Hell und komfortabel','Ideal für Paare oder kleine Familien','Terrasse und Familienbereich','Perfekt für Paare','Praktisch und mediterran','Für Familien','Geräumig','Maximale Kapazität','Urlaub in der Gruppe','Großes Wohnzimmer','Familien-Duplex','Duplex mit Charakter','Komfortabel und praktisch','Familienurlaub']},
nl:{apartment:'Appartement',studio:'Studio',duplex:'Duplex',people:'personen',bedroom:'slaapkamer',bedrooms:'slaapkamers',beach:'Strand op 50 m',consult:'Beschikbaarheid',descs:['Ruim en gezinsvriendelijk','Licht en comfortabel','Ideaal voor een stel of klein gezin','Terras en gezinsruimte','Perfect voor een stel','Praktisch en mediterraan','Voor gezinnen','Ruim','Maximale capaciteit','Vakantie met groep','Ruime woonkamer','Familieduplex','Duplex met karakter','Comfortabel en praktisch','Gezinsvakantie']}
};
let currentLang='es', currentReview=0;
function initScores(){document.getElementById('bookingScore').textContent=SITE_CONFIG.bookingScore;document.getElementById('googleScore').textContent=SITE_CONFIG.googleScore;document.getElementById('yearsExperience').textContent=SITE_CONFIG.yearsExperience}
function renderApartments(lang=currentLang){const grid=document.getElementById('aptGrid');if(!grid)return;const t=APT_LANG[lang]||APT_LANG.es;grid.innerHTML=APARTMENTS.map((a,i)=>{const isStudio=a.name.includes('Estudio'),isDuplex=a.name.includes('Dúplex');const name=`${isStudio?t.studio:isDuplex?t.duplex:t.apartment} N.º ${a.n}`;const p=a.people.split(' ')[0];const bd=a.beds.split(' ')[0];const beds=a.beds==='Estudio'?t.studio:`${bd} ${bd==='1'?t.bedroom:t.bedrooms}`;return `<article class="apt-mini reveal show"><img src="${a.img}" alt="${name} - El Bergantí, Canyelles Petites" loading="lazy"><div><span class="apt-number">Nº ${a.n}</span><h3>${name}</h3><p>${t.descs[i]}</p><ul><li>👥 ${p} ${t.people}</li><li>🛏️ ${beds}</li><li>🏖️ ${t.beach}</li></ul><a href="https://wa.me/34696906510?text=Hola%2C%20quiero%20consultar%20disponibilidad%20del%20${encodeURIComponent(name)}" class="mini-link">${t.consult} →</a></div></article>`}).join('')}
function initNav(){const nav=document.getElementById('nav'),burger=document.getElementById('burger'),menu=document.getElementById('mobileMenu');window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',window.scrollY>20),{passive:true});burger?.addEventListener('click',()=>menu.classList.toggle('open'));menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')))}
function initReveal(){const items=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){items.forEach(i=>i.classList.add('show'));return}const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}})},{threshold:.12});items.forEach(i=>io.observe(i))}
function paintReview(){const arr=TESTIMONIALS[currentLang]||TESTIMONIALS.es;const text=document.getElementById('reviewText'),dots=document.getElementById('reviewDots');if(!text||!dots)return;if(currentReview>=arr.length)currentReview=0;text.textContent=arr[currentReview];dots.innerHTML=arr.map((_,i)=>`<i class="review-dot ${i===currentReview?'on':''}"></i>`).join('')}
function initReviews(){const prev=document.getElementById('prevReview'),next=document.getElementById('nextReview');prev?.addEventListener('click',()=>{const arr=TESTIMONIALS[currentLang]||TESTIMONIALS.es;currentReview=(currentReview-1+arr.length)%arr.length;paintReview()});next?.addEventListener('click',()=>{const arr=TESTIMONIALS[currentLang]||TESTIMONIALS.es;currentReview=(currentReview+1)%arr.length;paintReview()});setInterval(()=>{const arr=TESTIMONIALS[currentLang]||TESTIMONIALS.es;currentReview=(currentReview+1)%arr.length;paintReview()},6500);paintReview()}
function applyI18n(lang){currentLang=lang;const dict=(window.I18N&&window.I18N[lang])?window.I18N[lang]:window.I18N?.es;if(!dict)return;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(dict[key])el.textContent=dict[key]});document.querySelectorAll('[data-i18n-html]').forEach(el=>{const key=el.dataset.i18nHtml;if(dict[key])el.innerHTML=dict[key]});document.querySelectorAll('[data-lang]').forEach(a=>a.classList.toggle('on',a.dataset.lang===lang));localStorage.setItem('bergantiLang',lang);renderApartments(lang);paintReview()}
function initLang(){const saved=localStorage.getItem('bergantiLang')||'es';applyI18n(saved);document.querySelectorAll('[data-lang]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();applyI18n(a.dataset.lang)}))}
document.addEventListener('DOMContentLoaded',()=>{initScores();initNav();initReviews();initLang();initReveal()});
